
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.wcfreservavehiculos_business.CancelarReservaRequest;
import org.datacontract.schemas._2004._07.wcfreservavehiculos_business.CancelarReservaResponse;
import org.datacontract.schemas._2004._07.wcfreservavehiculos_business.ConsultarCiudadesRequest;
import org.datacontract.schemas._2004._07.wcfreservavehiculos_business.ConsultarCiudadesResponse;
import org.datacontract.schemas._2004._07.wcfreservavehiculos_business.ConsultarPaisesResponse;
import org.datacontract.schemas._2004._07.wcfreservavehiculos_business.ConsultarReservasRequest;
import org.datacontract.schemas._2004._07.wcfreservavehiculos_business.ConsultarReservasResponse;
import org.datacontract.schemas._2004._07.wcfreservavehiculos_business.ConsultarVehiculosDisponiblesResponse;
import org.datacontract.schemas._2004._07.wcfreservavehiculos_business.ConsultarVehiculosRequest;
import org.datacontract.schemas._2004._07.wcfreservavehiculos_business.ReservarVehiculoRequest;
import org.datacontract.schemas._2004._07.wcfreservavehiculos_business.ReservarVehiculoResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWCFReservaVehiculos", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    generated.ObjectFactory.class,
    org.datacontract.schemas._2004._07.servicioweb.ObjectFactory.class,
    org.datacontract.schemas._2004._07.wcfreservavehiculos_business.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IWCFReservaVehiculos {


    /**
     * 
     * @param consultarCiudadesRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.wcfreservavehiculos_business.ConsultarCiudadesResponse
     * @throws IWCFReservaVehiculosConsultarCiudadesStatusResponseFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultarCiudades", action = "http://tempuri.org/IWCFReservaVehiculos/ConsultarCiudades")
    @WebResult(name = "ConsultarCiudadesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarCiudades", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarCiudades")
    @ResponseWrapper(localName = "ConsultarCiudadesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarCiudadesResponse")
    public ConsultarCiudadesResponse consultarCiudades(
        @WebParam(name = "ConsultarCiudadesRequest", targetNamespace = "http://tempuri.org/")
        ConsultarCiudadesRequest consultarCiudadesRequest)
        throws IWCFReservaVehiculosConsultarCiudadesStatusResponseFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.wcfreservavehiculos_business.ConsultarPaisesResponse
     * @throws IWCFReservaVehiculosConsultarPaisesStatusResponseFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultarPaises", action = "http://tempuri.org/IWCFReservaVehiculos/ConsultarPaises")
    @WebResult(name = "ConsultarPaisesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarPaises", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarPaises")
    @ResponseWrapper(localName = "ConsultarPaisesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarPaisesResponse")
    public ConsultarPaisesResponse consultarPaises()
        throws IWCFReservaVehiculosConsultarPaisesStatusResponseFaultFaultMessage
    ;

    /**
     * 
     * @param consultarVehiculosRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.wcfreservavehiculos_business.ConsultarVehiculosDisponiblesResponse
     * @throws IWCFReservaVehiculosConsultarVehiculosDisponiblesStatusResponseFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultarVehiculosDisponibles", action = "http://tempuri.org/IWCFReservaVehiculos/ConsultarVehiculosDisponibles")
    @WebResult(name = "ConsultarVehiculosDisponiblesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarVehiculosDisponibles", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarVehiculosDisponibles")
    @ResponseWrapper(localName = "ConsultarVehiculosDisponiblesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarVehiculosDisponiblesResponse")
    public ConsultarVehiculosDisponiblesResponse consultarVehiculosDisponibles(
        @WebParam(name = "ConsultarVehiculosRequest", targetNamespace = "http://tempuri.org/")
        ConsultarVehiculosRequest consultarVehiculosRequest)
        throws IWCFReservaVehiculosConsultarVehiculosDisponiblesStatusResponseFaultFaultMessage
    ;

    /**
     * 
     * @param reservarVehiculoRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.wcfreservavehiculos_business.ReservarVehiculoResponse
     * @throws IWCFReservaVehiculosReservarVehiculoStatusResponseFaultFaultMessage
     */
    @WebMethod(operationName = "ReservarVehiculo", action = "http://tempuri.org/IWCFReservaVehiculos/ReservarVehiculo")
    @WebResult(name = "ReservarVehiculoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReservarVehiculo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReservarVehiculo")
    @ResponseWrapper(localName = "ReservarVehiculoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReservarVehiculoResponse")
    public ReservarVehiculoResponse reservarVehiculo(
        @WebParam(name = "ReservarVehiculoRequest", targetNamespace = "http://tempuri.org/")
        ReservarVehiculoRequest reservarVehiculoRequest)
        throws IWCFReservaVehiculosReservarVehiculoStatusResponseFaultFaultMessage
    ;

    /**
     * 
     * @param consultarReservaRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.wcfreservavehiculos_business.ConsultarReservasResponse
     * @throws IWCFReservaVehiculosConsultarReservaStatusResponseFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultarReserva", action = "http://tempuri.org/IWCFReservaVehiculos/ConsultarReserva")
    @WebResult(name = "ConsultarReservaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarReserva", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarReserva")
    @ResponseWrapper(localName = "ConsultarReservaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarReservaResponse")
    public ConsultarReservasResponse consultarReserva(
        @WebParam(name = "ConsultarReservaRequest", targetNamespace = "http://tempuri.org/")
        ConsultarReservasRequest consultarReservaRequest)
        throws IWCFReservaVehiculosConsultarReservaStatusResponseFaultFaultMessage
    ;

    /**
     * 
     * @param cancelarReservaRequest
     * @return
     *     returns org.datacontract.schemas._2004._07.wcfreservavehiculos_business.CancelarReservaResponse
     * @throws IWCFReservaVehiculosCancelarReservaStatusResponseFaultFaultMessage
     */
    @WebMethod(operationName = "CancelarReserva", action = "http://tempuri.org/IWCFReservaVehiculos/CancelarReserva")
    @WebResult(name = "CancelarReservaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelarReserva", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelarReserva")
    @ResponseWrapper(localName = "CancelarReservaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelarReservaResponse")
    public CancelarReservaResponse cancelarReserva(
        @WebParam(name = "CancelarReservaRequest", targetNamespace = "http://tempuri.org/")
        CancelarReservaRequest cancelarReservaRequest)
        throws IWCFReservaVehiculosCancelarReservaStatusResponseFaultFaultMessage
    ;

}
