/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package iaewtpi

import org.datacontract.schemas._2004._07.servicioweb.Credentials
import org.datacontract.schemas._2004._07.wcfreservavehiculos_business.ConsultarCiudadesRequest
import org.datacontract.schemas._2004._07.wcfreservavehiculos_business.ConsultarVehiculosRequest
import org.tempuri.*
import java.lang.Exception
import java.net.Authenticator
import java.net.PasswordAuthentication
import javax.xml.ws.BindingProvider
import javax.xml.ws.handler.MessageContext

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {

    try {
        val cliente = org.tempuri.WCFReservaVehiculos()
        val port = cliente.basicHttpBindingIWCFReservaVehiculos
        val bind = port as BindingProvider
        bind.requestContext[BindingProvider.USERNAME_PROPERTY] = "grupo_nro1"
        bind.requestContext[BindingProvider.PASSWORD_PROPERTY] = "AzArobmjV0"

        println(port.requestContext[BindingProvider.USERNAME_PROPERTY])
        println(port.requestContext[BindingProvider.PASSWORD_PROPERTY])


        val paises = port.consultarPaises().paises.value.paisEntity

        for (pais in paises) {
            println(pais.nombre.value)
        }

    } catch (e: IWCFReservaVehiculosConsultarPaisesStatusResponseFaultFaultMessage) {
        println(e.faultInfo.errorCode)
        println(e.message)
    }

}
